# Generated by Django 5.0.7 on 2024-07-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                default='2024-01-01',
                help_text="Введите дату производства продукта",
                verbose_name="Дата производства продукта",
            ),
            preserve_default=False,
        ),
    ]
