# Generated by Django 5.0.7 on 2024-07-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото продукта",
                null=True,
                upload_to="catalog/photo",
                verbose_name="Фото",
            ),
        ),
    ]
