# Generated by Django 5.0.7 on 2024-07-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_rename_address_contactinfo_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactinfo",
            name="email",
        ),
    ]
