# Generated by Django 5.0.7 on 2024-07-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_remove_contactinfo_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slog", models.SlugField()),
                ("content", models.TextField()),
                ("preview", models.ImageField(upload_to="catalog/photo")),
                ("date_creation", models.DateTimeField()),
                ("publication_sign", models.BooleanField()),
                ("number_views", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание категории"
            ),
        ),
    ]
