# Generated by Django 5.0.7 on 2024-07-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_product_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="number_views",
        ),
        migrations.AddField(
            model_name="blog",
            name="views_counter",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Счётчик просмотров",
            ),
        ),
    ]
