# Generated by Django 5.0.7 on 2024-07-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_remove_blog_number_views_blog_views_counter_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["publication_sign", "-date_creation"],
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="date_creation",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото продукта",
                null=True,
                upload_to="catalog/photo",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="publication_sign",
            field=models.BooleanField(default=False, verbose_name="Опубликовано?"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Счётчик просмотров",
            ),
        ),
    ]
