# Generated by Django 5.0.7 on 2024-07-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_blog_options_alter_blog_content_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="slog",
            new_name="slug",
        ),
        migrations.AlterField(
            model_name="blog",
            name="date_creation",
            field=models.DateTimeField(verbose_name="Дата создания"),
        ),
    ]
