# Generated by Django 5.0.7 on 2024-07-28 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_alter_blog_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название продукта",
                        max_length=100,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "created_at",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Введите год создания",
                        null=True,
                        verbose_name="Год создания",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите название категории",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parents",
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт родитель",
                "verbose_name_plural": "Продукты родительские",
                "ordering": ["category", "name"],
            },
        ),
    ]
