# Generated by Django 5.0.7 on 2024-07-28 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        help_text="Введите номер версии", verbose_name="Номер версии"
                    ),
                ),
                (
                    "version_name",
                    models.CharField(
                        blank=True,
                        help_text="Введите название версии",
                        null=True,
                        verbose_name="Название версии",
                    ),
                ),
                (
                    "indication_current_version",
                    models.BooleanField(
                        default=False,
                        help_text="Введите признак текущей версии",
                        verbose_name="Признак текущей версии.",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия продукта",
                "verbose_name_plural": "Версии продуктов",
                "ordering": ["indication_current_version", "version_number"],
            },
        ),
        migrations.DeleteModel(
            name="Parent",
        ),
    ]
