# Generated by Django 4.2.2 on 2024-08-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "name"],
                "permissions": [
                    ("can_edit_category", "Редактировать категории"),
                    ("can_edit_description", "Редактировать описание продукта"),
                    ("can_cancel_publication", "Отмена публикации продукта"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
