# Generated by Django 4.2.2 on 2024-08-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publication_sign",
            field=models.BooleanField(default=False, verbose_name="Опубликовано?"),
        ),
    ]
